### ISSUE TITLE
Bug: "SvgAttr.in" and "SvgAttr.type" are invalid generated code

### ISSUE THREAD

**Issue by peteygao** [dillonkearns/elm-review-html-to-elm#13]
Currently the review rule generates `SvgAttr.in` and `SvgAttr.type`, but they should be `in_` and `type_` since both `in` and `type` are reserved keywords.

**Comment by dillonkearns** [comment]
Thanks for reporting the error @peteygao! This is fixed on the site and in the Elm package now 👍
