### ISSUE TITLE
Text nodes should retain whitespace

### ISSUE THREAD

**Issue by cllns** [dillonkearns/elm-review-html-to-elm#16]
Amazing and helpful tool!

I ran into a small issue when copying HTML from TailwindUI into elm-to-html.com 

The issue is that `text` nodes are run through [`String.trim`](https://github.com/dillonkearns/elm-review-html-to-elm/blob/39cdfd5512e01da623059396b6e4903bbcc24e0f/src/HtmlToTailwind.elm#L48-L63). This makes for cleaner strings, but whitespace has semantic meaning in text nodes, which is lost. 

(I could see 'fixing' this possibly generating very long trailing spaces and new lines, so maybe any whitespace could be collapsed into a single space? Not sure if that's actually tenable.)

Here is the original/expected HTML, followed by the HTML generated by Elm, after having been passed through elm-to-html.com
```diff
-<p>Faucibus commodo massa rhoncus, volutpat. <strong>Dignissim</strong> sed <strong>eget risus enim</strong>.</p>
+<p>Faucibus commodo massa rhoncus, volutpat.<strong>Dignissim</strong>sed<strong>eget risus enim</strong></p>
```

Expected:
<img width="758" alt="image" src="https://user-images.githubusercontent.com/632942/161128189-b224478c-b63d-41ba-ae82-30e8655108ff.png">

Actual:
<img width="820" alt="image" src="https://user-images.githubusercontent.com/632942/161128264-2d54e022-0c70-47a9-a817-d88243221cda.png">

**Comment by dillonkearns** [comment]
Hey! Thank you for reporting the issue and finding the relevant code.

```elm
                trimmed : String
                trimmed =
                    String.trim textBody
                        |> Regex.replace
                            (Regex.fromString "\\s+"
                                |> Maybe.withDefault Regex.never
                            )
                            (\_ -> " ")

```

This is the current implementation (as you linked to). I wonder if the regex replace is sufficient and maybe just removing the `String.trim` would handle it correctly?

**Comment by dillonkearns** [comment]
Okay, I think this might address the issues. Here's a preview of the deployed site that you can play around with, any thoughts?

https://deploy-preview-20--html-to-elm-tailwind.netlify.app/

The one case that comes to mind that I'm not sure about is if whitespace needs to be preserved within nodes that have nothing but whitespace or if it is safe to remove all whitespace within whitespace-only nodes. Otherwise it's seeming pretty good.

**Comment by cllns** [comment]
Thanks @dillonkearns. Sorry I didn't look at it in a timely manner but the preview link looks great

**Comment by dillonkearns** [comment]
No problem, thanks for taking a look! It's live now on the site and new package release. Thanks again for reporting the issue! 🙏
