### ISSUE TITLE
Tailwind colors with 3 words prefix not handled

### ISSUE THREAD

**Issue by dennistruemper** [dillonkearns/elm-review-html-to-elm#25]
Hi, I just came across `ring-offset-purple-500` which is not of the pattern word-word-number, but word-word-word-number.  :/ 

There is always an exception to the rule, should haven known that.

There is always a regex to make thinks worse, so you could use `(\w+\W?\w*)\W(\w+\W\d{2,3})` .

If you think this is a valid solution, let me know, I'd like to open a PR.

**Comment by dillonkearns** [comment]
Seems to be inline with the current approach, so yeah may as well go for it I think! If you're still up for a PR that would definitely be welcome!

**Comment by dennistruemper** [comment]
just opened #28

**Comment by dillonkearns** [comment]
Fixed by #28.

**Comment by dillonkearns** [comment]
Thanks so much!

**Comment by dennistruemper** [comment]
Happy to help ☺️ thanks for elm-radio
