### ISSUE TITLE
Escape quotation marks inside strings

### ISSUE THREAD

**Issue by MartinSStewart** [dillonkearns/elm-review-html-to-elm#26]
I noticed on the https://html-to-elm.com/ website, `"` inside strings are not escaped in the generated Elm code. For example `"Test"` will generate `Html.text ""Test""`

**Comment by dillonkearns** [comment]
Thanks for reporting the issue! This definitely looks like a bug.

I don't have bandwidth at the moment, if somebody wants to tackle this this would be a pretty good first contribution to this project.

**Comment by mateusfpleite** [comment]
Had the same problem today and I think I managed to fix it in #29

**Comment by dillonkearns** [comment]
Thank you for the fix @mateusfpleite! Merged.
