### ISSUE TITLE
Better styling for the web view of this tool

### ISSUE THREAD

**Issue by dillonkearns** [dillonkearns/elm-review-html-to-elm#5]
Why not use https://matheus23.github.io/elm-tailwind-modules to style the site itself? 😄

Some things that need improvement:

- Text wrapping for the output `pre` section
- Syntax highlighting would be great for the Elm output (this package is pretty nice for doing that in pure Elm https://package.elm-lang.org/packages/pablohirafuji/elm-syntax-highlight/latest/)
- Some intro text giving the name of the tool, some useful links, and context on what the tool does and how to use it
- Syntax highlighting would be a plus for the input HTML area, but this is probably the lowest priority of any of these improvements

**Comment by matheus23** [comment]
And why not use https://github.com/dillonkearns/html-to-elm-tailwind-modules to generate the skeleton for the page from some tailwindui dashboard component that will become the new web view of this tool? 

:smiling_imp:

**Comment by dillonkearns** [comment]
🐔 🔄 🥚

🤔

**Comment by dillonkearns** [comment]
The ultimate self-bootstrapping process, love it ❤️

**Comment by dillonkearns** [comment]
The self-bootstrapping process is complete 🚀

**Comment by matheus23** [comment]
I love it! :heart:
