### ISSUE TITLE
Finish regex replace rules to normalize Elm names

### ISSUE THREAD

**Issue by dillonkearns** [dillonkearns/elm-review-html-to-elm#8]
One example that isn't yet implemented:

```html
<div class="space-x-1.5">
```
Generates:

```elm
Tw.space_x_1.5
```

And should instead generate:
```elm
Tw.space_x_1_dot_5
```

See full list of rules https://github.com/matheus23/elm-tailwind-modules/blob/cd5809505934ff72c9b54fd1e181f67b53af8186/src/helpers.ts#L24-L59.

**Comment by dillonkearns** [comment]
I'm not aware of any remaining normalization rules that need to be applied.

@matheus23 do you think this code covers all the needed logic to scrub the names, or is there anything missing? https://github.com/dillonkearns/html-to-elm-tailwind-modules/blob/89c38a11c2eb9f3bbe68ffee2d886359a8bcd252/src/HtmlToTailwind.elm#L245-L255

**Comment by matheus23** [comment]
Ah, I see. You copied the logic and removed unused stuff like the prefix and camel casing logic (which is essentially dead code in elm-tailwind-modules) and anything handling variants.

Looks good to me :)

**Comment by dillonkearns** [comment]
Excellent, I think this is in good shape for now then 👍
